server:
  port: 8085

spring:
  application:
    name: expensys
  cloud:
    config:
      enabled: false

logging:
  level:
    org.springframework.web: DEBUG

lb:
  algorithms:
    - algorithm: ROUND_ROBIN
      enabled: false
    - algorithm: WEIGHTED_ROUND_ROBIN
      enabled: false
    - algorithm: LEAST_CONNECTIONS
      enabled: true
  servers:
    - name: Server1
      url: http://localhost:8080
      weight: 1
    - name: Server2
      url: http://localhost:8081
      weight: 2
    - name: Server3
      url: http://localhost:8082
      weight: 2
    - name: Server4
      url: http://localhost:8083
      weight: 4
